# Generated by Django 5.0.2 on 2024-03-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_gamejam'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(default='arcadiaCover.png', upload_to='portadas/'),
        ),
    ]
