# Generated by Django 5.0.2 on 2024-03-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_juego_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desarrollador',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='gamejam',
            name='imagen',
            field=models.ImageField(default='arcadiaCover.png', upload_to='media/portadas/'),
        ),
        migrations.AddField(
            model_name='juego',
            name='trailer',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(default='arcadiaCover.png', upload_to='media/portadas/'),
        ),
    ]
