# Generated by Django 5.0.2 on 2024-03-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_desarrollador_descripcion_gamejam_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='trailer',
            field=models.FilePathField(path='media/videos/', recursive=True),
        ),
    ]
