# Generated by Django 5.0.2 on 2024-03-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='arcadiaAvatar.jpg', upload_to='media/avatars/'),
        ),
    ]
